# Generated by Django 5.2.4 on 2025-08-15 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('supplier_company', models.CharField(blank=True, max_length=100, null=True)),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('score', models.FloatField()),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('passed', models.BooleanField(default=False)),
                ('results', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TEXT', 'Text Answer')], default='MCQ', max_length=10)),
                ('correct_answer', models.TextField(blank=True, help_text='Chỉ áp dụng cho câu hỏi dạng TEXT', null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('max_score', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ExamCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('questions', models.ManyToManyField(to='polls.question')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('label', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
        ),
    ]
