# Generated by Django 5.2.4 on 2025-08-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_choice_votes_remove_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='label',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1),
        ),
    ]
