# Generated by Django 5.2.4 on 2025-08-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_choice_is_correct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('total', models.IntegerField()),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
