# Generated by Django 5.2.4 on 2025-08-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_examresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
