# Generated by Django 5.2.4 on 2025-08-08 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_examresult_passed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='total',
        ),
    ]
