# Generated by Django 5.2.4 on 2025-08-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_remove_examresult_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
