# Generated by Django 5.2.4 on 2025-08-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_examresult_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
