# Generated by Django 5.2.4 on 2025-08-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_examresult_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TEXT', 'Text Answer')], default='MCQ', max_length=10),
        ),
    ]
