# Generated by Django 5.2.4 on 2025-08-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True, help_text='Chỉ áp dụng cho câu hỏi dạng TEXT', null=True),
        ),
    ]
