# Generated by Django 5.2.4 on 2025-08-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_question_correct_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('questions', models.ManyToManyField(to='polls.question')),
            ],
        ),
    ]
