# Generated by Django 5.2.4 on 2025-08-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_examcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='max_score',
            field=models.IntegerField(default=1),
        ),
    ]
