# Generated by Django 5.2.4 on 2025-08-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_question_keywords_question_max_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='max_score',
            field=models.FloatField(default=0),
        ),
    ]
