# Generated by Django 5.2.4 on 2025-08-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_alter_examresult_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='supplier_company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
