# Generated by Django 5.2.4 on 2025-08-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_examresult_phone_examresult_supplier_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
